# Generated by Django 5.0.4 on 2024-05-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
