# Generated by Django 5.0.4 on 2024-05-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_remove_grade_assignment_grade_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
